### ISSUE TITLE
[To-Do][6.0 Pre] To-Dos and Predictions

### ISSUE THREAD

**Issue by ClayLivince** [ClayLivince/GarlandTools#1]
- [ ] Triple Triad Finishing
    - [ ] NPC Battles
    - [ ] Source Category
- [x] Collab with Otterbot and support advanced /search command
- [x] HQ item removing
- [ ] EN/JP data for unreleased items in China
- [ ] Garland-driven Mappy by ACT triggers or Machina, for Chinese client
    - [ ] php api  [Working on this]
    - [ ] uploader
- [ ] Reworked map and item display structure, for gather time displaying in item block
